apiVersion: batch/v1
kind: Job
metadata:
  name: pyspark-client-job
  namespace: sail
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: sail-user
      containers:
        - name: pyspark-client
          image: pyspark-client:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_LOG
              value: info
          args: ["client.py"]
